version: '3.3'
services:
  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: 'nestsample'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
volumes:
  database: