# ref: https://baumannalexj.medium.com/connect-your-db-tool-to-a-dockerized-mysql-server-container-bc18853524ed

version: '3.3'
services:
  db:
    container_name: github-chanonhongthong-nestsample
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: 'nestsample'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database:/var/lib/mysql
volumes:
  database: